version: '3'

volumes:
  postgres_data:

services:
  django:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        MODE: "--with dev"
    depends_on:
      - postgres
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: postgresql
    restart: always
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8080:8080"
